apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-app-v2
  labels:
    app: canary-app
    version: v1.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canary-app
      version: v1.1
  template:
    metadata:
      labels:
        app: canary-app
        version: v1.1
    spec:
      containers:
      - name: canary-app
        image: abivarmang/canary-app:v1.1
        ports:
        - containerPort: 3000
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
