apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mobile-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbivarmanAb/Devops_projects/my-gitops-app
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: mobile-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
