apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: mobile-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: mobile-app
spec:
  selector:
    app: simple-web
  ports:
  - port: 80
    targetPort: 80
